[package]
name = "alien_swarm"
version = "0.1.0"
edition = "2021"

[dependencies]
seq-macro = "0.3.3"
bevy = "0.10.1"
bevy_ecs_tilemap = "0.10.0"
bitfield-derive = "0.2.1"
partial-min-max = "0.4.0"
rand = "0.8.5"
ron = "0.8.0"
random = "0.14.0"
bevy_framepace = "0.12.1"
bevy_tweening = "0.7.0"
bevy_screen_diags = { git = "https://github.com/LemonjamesD/bevy_screen_diags_0.10.git", version = "0.5.2" }
paste = "1.0.12"
num-traits = "0.2.15"
