---
  name: "{{variant.name}} Rose"
  category: "Plant"
  tileId: "t-4{{variant}}"
  itemId: "i-4{{variant}}"
  tileTexture: "tiles/{{variant}}_rose.png"
  itemTexture: "item/{{variant}}_rose.png"
  variants:
    - red:
        default: true
        name: "Red"
        weight: 40.0
        toughness: 0.0
    - blue:
        name: "Blue"
        weight: 40.0
        toughness: 0.0
  tileDrops:
    - "i-4{{variant}}"