[package]
name = "graphical_alien_swarm_proc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.66"
quote = "1.0.31"
regex = "1.9.1"
syn = { version = "2.0.26", features = ["derive", "full", "parsing"] }
