# Fully filled out config for items/tiles/tileitems
---
  name: "Default" # Name for the Tile/Item
  category: "None"
  tileId: "t-default" # Id for the tile
  itemId: "i-default" # Id for the item
  tileTexture: "tiles/air.png" # Default Tile texture
  itemTexture: "tiles/air.png" # Default Item texture
  variants:
    - default:
        name: "Default"
        default: true
    - expressive:
        name: "Expressive Default" # Name for the variant
        tileId: "t-defaultExpressive" # Overrides the default TileId
        itemId: "i-defaultExpressive" # Id for the item
        weight: 0.0 # How much the weight of the item is
        toughness: 0.0 # Minimum tool strength to break
        tileTexture: "tiles/air.png" # Override default Tile texture
        itemTexture: "tiles/air.png" # Override default Item texture
        tileDrops: # Overrides the tilesDrops
          - "i-defaultExpressive"
  tileDrops: # What the tile would drop
    - "i-default"
  autotile: # If the tile is autotiling
    - tile: "t-default" # What tile to autotile with
      default: "tiles/air.png"
      nw: "tiles/air.png"
      n: "tiles/air.png"
      ne: "tiles/air.png"
      w: "tiles/air.png"
      e: "tiles/air.png"
      sw: "tiles/air.png"
      s: "tiles/air.png"
      se: "tiles/air.png"