name: Docs

on:
  push:
    paths:
      - "src"
      - "graphical_alien_swarm_proc_macros"
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
    - name: Docs
      run: cargo doc --no-deps
    - name: Add Docs
      run: mv ./target/doc/alien_swarm ./docs
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v5
      with:
         gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
         passphrase: ${{ secrets.GPG_PASSPHRASE }}
         git_user_signingkey: true
         git_commit_gpgsign: true
         trust_level: 5
    - name: Commit changes
      run: |
        git add .
        git commit -S -m "Generated Docs"
        git push
