name: Docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependencies
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev
    - name: Docs
      run: cargo doc --no-deps
    - name: Add Docs
      run: mv ./target/doc/alien_swarm ./docs
    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v1
      env:
         gpg_private_key: ${{ secrets.GPG_SIGNING_KEY }}
         passphrase: ${{ secrets.GPG_PASSPHRASE }}
         git_user_signingkey: true
         git_commit_gpgsign: true
    - name: Tell git who I am
      run: |
        git config --global user.email "lemonjameslem@protonmail.com"
        git config --global user.name "LemonjamesD"
    - name: Add changes
      run: git add .
    - name: Commit changes
      run: git commit -S -m "Generated Docs"
    - name: Push changes
      run: git push origin HEAD:main
